# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cdde4f1dd34faa511919ea94334f86d01e99daaf88db88f3053ee93d12212a7b15cee090fe05ffa3246a963f18eb5880407036e0a26012efe379bde23a5b651

test:
  secret_key_base: e0a97a4311fa3c6d0ec6593f943ca1a2b9a2de0b98ed4ce8be61b805e9b259170438ce74b7afa2540299ec23451e40ca21a244c031ec629106c992e9fe66df00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
